### PR TITLE
Added github action workflow, plus needed tests

### PR DESCRIPTION
**Pull request by m88614**

### CODE REVIEW

**Comment by zhenik** [comment]
I do not think that github-actions runner will be able to run this pipeline, due to resource limitation

**Comment by m88614** [comment]
> I do not think that github-actions runner will be able to run this pipeline, due to resource limitation

I'll fully admit I forgot about that. Did learn about actions though!

**Comment by zhenik** [comment]
It would be any way useful to have target `test` in Makefile, be able to run tests locally

**Comment by m88614** [comment]
> It would be any way useful to have target `test` in Makefile, be able to run tests locally

I agree with that.

**Comment by m88614** [comment]
Okay, so miraculously the tests passed. It says black on white that the machines have 7gb RAM available [ref](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners).

I would still like to close this PR, considering the checks should technically not pass. Anyone against that?

**Comment by fredrikhgrelland** [comment]
> > It would be any way useful to have target `test` in Makefile, be able to run tests locally
> 
> ~I agree with that.~ Considering terraform runs in attached state an ansible task checking the health of all services is redundant. The terraform-task would never exit without everything being healthy.

Are you sure about this? Can you confirm that we have all services passed?

**Comment by fredrikhgrelland** [comment]
Strange.. It sure reports two cores and two threads https://github.com/fredrikhgrelland/data-mesh/pull/91/checks?check_run_id=780740006#step:3:1120 on "mac os level" but the hardware is 4 cores: https://github.com/fredrikhgrelland/data-mesh/pull/91/checks?check_run_id=780740006#step:3:1009 and memory is 12GB ? https://github.com/fredrikhgrelland/data-mesh/pull/91/checks?check_run_id=780740006#step:3:1007

**Comment by fredrikhgrelland** [comment]
Pretty decent CPU also https://github.com/fredrikhgrelland/data-mesh/pull/91/checks?check_run_id=780740006#step:3:1069

**Comment by fredrikhgrelland** [comment]
This has to be the actual hardware: https://everymac.com/systems/apple/mac_pro/specs/mac-pro-six-core-3.5-xeon-e5-gray-black-cylinder-late-2013-specs.html

**Comment by fredrikhgrelland** [comment]
Plenty med disk også: https://github.com/fredrikhgrelland/data-mesh/pull/91/checks?check_run_id=780826831#step:4:51165

**Comment by m88614** [comment]
Say what now... nice detective work, haha.
I guess we might as well keep the tests for now then, and remove it later if it for some reason starts failing.

**Comment by m88614** [comment]
> Are you sure about this? Can you confirm that we have all services passed?

That answer was based on what you said earlier, which was that the `nomad_job` resource would run until the service is healthy in nomad, and by extension, consul.

After a little digging: [ref](https://github.com/terraform-providers/terraform-provider-nomad/pull/64/files), if `detach = false`, the provider will keep running until the deployment is successful, or it fails and returns an error.

**Pull request merged**
